name:         Data-Google-Visualization-DataTable 
version:      0.03
version_from: lib/Data/Google/Visualization/DataTable.pm 
installdirs:  site
requires:
    "JSON::XS":                    2.00
distribution_type: module
generated_by: hand 
